[workspace]
resolver = "2"
members = [ "account",
    "gateway",
    "sdk",
    "chat",
    "extras",
    "channel",
]

[profile]

[profile.wasm-dev]
inherits = "dev"
opt-level = 1

[profile.server-dev]
inherits = "dev"

[profile.android-dev]
inherits = "dev"

#[workspace]
#resolver = "2"

