[package]
name = "mjk"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.8.1"
http-body-util = "0.1.2"
serde_json = "1.0.135"
tokio = "1.43.0"
tower = "0.5.2"
tower-http = { version = "0.6.2", features = ["compression-full", "decompression-full"] }
tracing = "0.1.41"
